export const LANGUAGE_MAP = {
  en: "English - United States",
  ru: "Русский - Россия",
};

export const LANGUAGE_CODES = Object.keys(LANGUAGE_MAP);

export const CURRENCIES = {
  USD: { symbol: "$", code: "USD", name: "Доллар США" },
  EUR: { symbol: "€", code: "EUR", name: "Евро" },
  RUB: { symbol: "₽", code: "RUB", name: "Российский рубль" },
  KZT: { symbol: "₸", code: "KZT", name: "Казахстанский тенге" },
  GBP: { symbol: "£", code: "GBP", name: "Фунт стерлингов" },
  AUD: { symbol: "A$", code: "AUD", name: "Австралийский доллар" },
  CAD: { symbol: "C$", code: "CAD", name: "Канадский доллар" },
  JPY: { symbol: "¥", code: "JPY", name: "Японская иена" },
  CHF: { symbol: "Fr", code: "CHF", name: "Швейцарский франк" },
  SEK: { symbol: "kr", code: "SEK", name: "Шведская крона" },
  NOK: { symbol: "kr", code: "NOK", name: "Норвежская крона" },
  DKK: { symbol: "kr", code: "DKK", name: "Датская крона" },
  NZD: { symbol: "NZ$", code: "NZD", name: "Новозеландский доллар" },
  SGD: { symbol: "S$", code: "SGD", name: "Сингапурский доллар" },
  HKD: { symbol: "HK$", code: "HKD", name: "Гонконгский доллар" },
  ZAR: { symbol: "R", code: "ZAR", name: "Южноафриканский рэнд" },
  MXN: { symbol: "$", code: "MXN", name: "Мексиканское песо" },
  BRL: { symbol: "R$", code: "BRL", name: "Бразильский реал" },
  INR: { symbol: "₹", code: "INR", name: "Индийская рупия" },
  CNY: { symbol: "¥", code: "CNY", name: "Китайский юань" },
  KRW: { symbol: "₩", code: "KRW", name: "Южнокорейская вона" },
  TRY: { symbol: "₺", code: "TRY", name: "Турецкая лира" },
  ILS: { symbol: "₪", code: "ILS", name: "Израильский шекель" },
  AED: { symbol: "د.إ", code: "AED", name: "Дирхам ОАЭ" },
  PLN: { symbol: "zł", code: "PLN", name: "Польский злотый" },
  CZK: { symbol: "Kč", code: "CZK", name: "Чешская крона" },
  HUF: { symbol: "Ft", code: "HUF", name: "Венгерский форинт" },
  THB: { symbol: "฿", code: "THB", name: "Таиландский бат" },
  MYR: { symbol: "RM", code: "MYR", name: "Малайзийский ринггит" },
  IDR: { symbol: "Rp", code: "IDR", name: "Индонезийская рупия" },
  PHP: { symbol: "₱", code: "PHP", name: "Филиппинское песо" },
  ARS: { symbol: "$", code: "ARS", name: "Аргентинское песо" },
  CLP: { symbol: "$", code: "CLP", name: "Чилийское песо" },
  COP: { symbol: "$", code: "COP", name: "Колумбийское песо" },
  PEN: { symbol: "S/", code: "PEN", name: "Перуанский соль" },
  VND: { symbol: "₫", code: "VND", name: "Вьетнамский донг" },
  TWD: { symbol: "NT$", code: "TWD", name: "Новый тайваньский доллар" },
  SAR: { symbol: "﷼", code: "SAR", name: "Саудовский риял" },
  EGP: { symbol: "£", code: "EGP", name: "Египетский фунт" },
  NGN: { symbol: "₦", code: "NGN", name: "Нигерийская найра" },
  PKR: { symbol: "₨", code: "PKR", name: "Пакистанская рупия" },
  BDT: { symbol: "৳", code: "BDT", name: "Бангладешская така" },
  LKR: { symbol: "₨", code: "LKR", name: "Шри-ланкийская рупия" },
  UAH: { symbol: "₴", code: "UAH", name: "Украинская гривна" },
  RON: { symbol: "lei", code: "RON", name: "Румынский лей" },
  BGN: { symbol: "лв", code: "BGN", name: "Болгарский лев" },
  HRK: { symbol: "kn", code: "HRK", name: "Хорватская куна" },
  ISK: { symbol: "kr", code: "ISK", name: "Исландская крона" },
  RSD: { symbol: "дин.", code: "RSD", name: "Сербский динар" },
  MDL: { symbol: "L", code: "MDL", name: "Молдавский лей" },
  GEL: { symbol: "₾", code: "GEL", name: "Грузинский лари" },
  AZN: { symbol: "₼", code: "AZN", name: "Азербайджанский манат" },
  BYN: { symbol: "Br", code: "BYN", name: "Белорусский рубль" },
  UZS: { symbol: "so'm", code: "UZS", name: "Узбекский сум" },
  TMT: { symbol: "m", code: "TMT", name: "Туркменский манат" },
  AMD: { symbol: "֏", code: "AMD", name: "Армянский драм" },
  KGS: { symbol: "с", code: "KGS", name: "Киргизский сом" },
  TJS: { symbol: "ЅМ", code: "TJS", name: "Таджикский сомони" },
  MNT: { symbol: "₮", code: "MNT", name: "Монгольский тугрик" },
  KHR: { symbol: "៛", code: "KHR", name: "Камбоджийский риель" },
  LAK: { symbol: "₭", code: "LAK", name: "Лаосский кип" },
  MMK: { symbol: "K", code: "MMK", name: "Мьянманский кьят" },
  NPR: { symbol: "₨", code: "NPR", name: "Непальская рупия" },
  BND: { symbol: "B$", code: "BND", name: "Брунейский доллар" },
  BHD: { symbol: ".د.ب", code: "BHD", name: "Бахрейнский динар" },
  OMR: { symbol: "ر.ع.", code: "OMR", name: "Оманский риал" },
  QAR: { symbol: "ر.ق", code: "QAR", name: "Катарский риал" },
  KWD: { symbol: "د.ك", code: "KWD", name: "Кувейтский динар" },
  JOD: { symbol: "د.ا", code: "JOD", name: "Иорданский динар" },
  LBP: { symbol: "ل.ل", code: "LBP", name: "Ливанский фунт" },
  SYP: { symbol: "£S", code: "SYP", name: "Сирийский фунт" },
  IQD: { symbol: "ع.د", code: "IQD", name: "Иракский динар" },
  IRR: { symbol: "﷼", code: "IRR", name: "Иранский риал" },
  AFN: { symbol: "؋", code: "AFN", name: "Афганский афгани" },
  MVR: { symbol: "ރ.", code: "MVR", name: "Мальдивская руфия" },
  BTN: { symbol: "Nu.", code: "BTN", name: "Бутанский нгултрум" },
  SCR: { symbol: "₨", code: "SCR", name: "Сейшельская рупия" },
  MUR: { symbol: "₨", code: "MUR", name: "Маврикийская рупия" },
  NAD: { symbol: "N$", code: "NAD", name: "Намибийский доллар" },
  BWP: { symbol: "P", code: "BWP", name: "Ботсванская пула" },
  ZMW: { symbol: "ZK", code: "ZMW", name: "Замбийская квача" },
};

export const CURRENCY_CODES = Object.keys(CURRENCIES);

export const LANGUAGES = {
  EN: "en",
  RU: "ru",
};

// Маппинг стран на валюты
export const COUNTRY_TO_CURRENCY = {
  US: "USD",
  RU: "RUB",
  KZ: "KZT",
  DE: "EUR",
  FR: "EUR",
  IT: "EUR",
  ES: "EUR",
};

// Маппинг стран на языки
export const COUNTRY_TO_LANGUAGE = {
  US: "en",
  RU: "ru",
  KZ: "ru",
};
